Warehouse.MVC/Models/SupplierView.cs
using WarehouseDTOs;

namespace Warehouse.MVC.Models
{
    public class SupplierView
    {
        public List<SupplierDTO> Suppliers { get; set; }
        public SupplierDTO Supplier { get; set; }
    }
}

Warehouse.MVC/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;
using Warehouse.MVC.Models;
using WarehouseDTOs;

namespace Warehouse.MVC.Controllers
{
    [Authorize]

    public class CategoryController : Controller
    {
        private string UrlGet = "https://localhost:7200/api/Category/WithProductCount";
        private string UrlGetId = "https://localhost:7200/api/Category";
        private string UrlCreate = "https://localhost:7200/api/Category";
        private string UrlUpdate = "https://localhost:7200/api/Category";

        public async Task<IActionResult> Index(int page = 1, int pageSize = 5, string search = null)
        {
            var categories = await GetCategoryAsync();
            var filteredCategories = categories?.ToList() ?? new List<CategoryProduct>();

            if (!string.IsNullOrEmpty(search))
            {
                filteredCategories = filteredCategories
                    .Where(c => c.CategoryName.Contains(search, StringComparison.OrdinalIgnoreCase))
                    .ToList();
            }

            int totalItems = filteredCategories.Count;
            int totalPages = (int)Math.Ceiling((double)totalItems / pageSize);
            var pagedData = filteredCategories.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            ViewBag.Page = page;
            ViewBag.TotalPages = totalPages;
            ViewBag.Search = search; // Lưu trạng thái tìm kiếm

            var view = new CategoryView
            {
                Categories = pagedData
            };
            return View(view);
        }
        public async Task<IActionResult> Update(int id)
        {
            var cat = await GetCategoryByIdAsync(id);
            var prodwc = await GetProductsByCategoryAsync(id);
            var view = new CategoryView
            {
                Products = prodwc,

                Category = cat
            };
            return View(view);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int id, CategoryUpdateDTO category)
        {

            using (HttpClient client = new HttpClient())
            {
                var json = JsonConvert.SerializeObject(category);
                var content = new StringContent(json, Encoding.UTF8, "application/json");

                HttpResponseMessage response = await client.PutAsync($"{UrlUpdate}/{id}", content);

                if (response.IsSuccessStatusCode)
                {
                    TempData["SuccessMessage"] = "Cập nhật thành công!!";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["ErrorMessage"] = "Cập nhật thất bại, vui lòng thử lại!";
                    return RedirectToAction("Index");
                }
            }

           
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CategoryDTO category)
        {
         

            string json = JsonConvert.SerializeObject(category);
            using (HttpClient client = new HttpClient())
            {
                var content = new StringContent(json, Encoding.UTF8, "application/json");
                HttpResponseMessage response = await client.PostAsync(UrlCreate, content);

                if (response.IsSuccessStatusCode)
                {
                    TempData["SuccessMessage"] = "Tạo danh mục thành công!!";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["ErrorMessage"] = "Danh mục đã tồn tại vu lòng thử lại!";
                    return RedirectToAction("Index");
                }
            }

            
        }
        private async Task<CategoryDTO> GetCategoryByIdAsync(int id)
        {
            using (HttpClient client = new HttpClient())
            {
                using (HttpResponseMessage res = await client.GetAsync($"{UrlGetId}/{id}"))
                {
                    if (res.IsSuccessStatusCode)
                    {
                        string data = await res.Content.ReadAsStringAsync();
                        return JsonConvert.DeserializeObject<CategoryDTO>(data);
                    }
                }
            }
            return null;
        }

        private async Task<List<CategoryProduct>> GetCategoryAsync()
        {
            using (HttpClient client = new HttpClient())
            {
                using (HttpResponseMessage res = await client.GetAsync(UrlGet))
                {
                    if (res.IsSuccessStatusCode)
                    {
                        string data = await res.Content.ReadAsStringAsync();
                        return JsonConvert.DeserializeObject<List<CategoryProduct>>(data);
                    }
                }
            }
            return new List<CategoryProduct>();
        }
        private async Task<List<ProductDTO>> GetProductsByCategoryAsync(int categoryId)
        {
            using (HttpClient client = new HttpClient())
            {
                using (HttpResponseMessage res = await client.GetAsync($"{UrlGetId}/{categoryId}/products"))
                {
                    if (res.IsSuccessStatusCode)
                    {
                        string data = await res.Content.ReadAsStringAsync();
                        return JsonConvert.DeserializeObject<List<ProductDTO>>(data);
                    }
                }
            }
            return new List<ProductDTO>();
        }

    }
}

Warehouse.MVC/Controllers/SupplierController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;
using Warehouse.MVC.Models;
using WarehouseDTOs;

namespace Warehouse.MVC.Controllers
{
    [Authorize]

    public class SupplierController : Controller
    {
        private string UrlGet = "https://localhost:7200/api/Supplier";


        [HttpGet]
        public async Task<IActionResult> Index(int page = 1, int pageSize = 5, string search = null)
        {
            var suppliers = await GetSupplierAsync();
            var filteredSuppliers = suppliers?.ToList() ?? new List<SupplierDTO>();

            if (!string.IsNullOrEmpty(search))
            {
                filteredSuppliers = filteredSuppliers
                    .Where(s => (s.Name?.Contains(search, StringComparison.OrdinalIgnoreCase) ?? false) ||
                                (s.Phone?.Contains(search, StringComparison.OrdinalIgnoreCase) ?? false) ||
                                (s.Email?.Contains(search, StringComparison.OrdinalIgnoreCase) ?? false))
                    .ToList();
            }

            int totalItems = filteredSuppliers.Count;
            int totalPages = (int)Math.Ceiling((double)totalItems / pageSize);
            var pagedData = filteredSuppliers.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            ViewBag.Page = page;
            ViewBag.TotalPages = totalPages;
            ViewBag.Search = search; 

            var view = new SupplierView
            {
                Suppliers = pagedData
            };
            return View(view);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(SupplierDTO supplier)
        {


            string json = JsonConvert.SerializeObject(supplier);
            using (HttpClient client = new HttpClient())
            {
                var content = new StringContent(json, Encoding.UTF8, "application/json");
                HttpResponseMessage response = await client.PostAsync(UrlGet, content);

                if (response.IsSuccessStatusCode)
                {
                    TempData["SuccessMessage"] = "Thêm NCC thành công!";
                    return RedirectToAction("Index");
                }
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var sup = await GetCategoryByIdAsync(id);
            var view = new SupplierView
            {
                Supplier = sup

            };
            return View(view);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int id, SupplierUpdateDTO supplier)
        {
          
            using (HttpClient client = new HttpClient())
            {
                var json = JsonConvert.SerializeObject(supplier);
                var content = new StringContent(json, Encoding.UTF8, "application/json");

                HttpResponseMessage response = await client.PutAsync($"{UrlGet}/{id}", content);

                if (response.IsSuccessStatusCode)
                {
                    TempData["SuccessMessage"] = "Cập nhật thành công!!";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["ErrorMessage"] = "Cập nhật thất bại, vui lòng thử lại!";
                    return RedirectToAction("Index");
                }
            }

            return View(supplier);
        }




        //=====================================
        private async Task<List<SupplierDTO>> GetSupplierAsync()
        {
            using (HttpClient client = new HttpClient())
            {
                using (HttpResponseMessage res = await client.GetAsync(UrlGet))
                {
                    if (res.IsSuccessStatusCode)
                    {
                        string data = await res.Content.ReadAsStringAsync();
                        return JsonConvert.DeserializeObject<List<SupplierDTO>>(data);
                    }
                }
            }
            return new List<SupplierDTO>();
        }


        private async Task<SupplierDTO> GetCategoryByIdAsync(int id)
        {
            using (HttpClient client = new HttpClient())
            {
                using (HttpResponseMessage res = await client.GetAsync($"{UrlGet}/{id}"))
                {
                    if (res.IsSuccessStatusCode)
                    {
                        string data = await res.Content.ReadAsStringAsync();
                        return JsonConvert.DeserializeObject<SupplierDTO>(data);
                    }
                }
            }
            return null;
        }
    }
}

Warehouse.MVC/Views/Supplier/Create.cshtml
@model Warehouse.MVC.Models.SupplierView
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Thêm NCC</h3>
        </div>
        <div class="card-body">
        <form asp-action="Create" method="post" enctype="multipart/form-data">
            <!-- Thông tin sản phẩm -->
            <div class="card mb-4">
                <div class="card-header">Thông NCC</div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="card-body">

                            <div class="mb-3">
                                <label class="form-label">Tên sản phẩm *</label>
                                <input type="text" class="form-control" name="name" placeholder="Tên danh mục" required>
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Phone</label>
                                <input type="text" class="form-control" name="phone" placeholder="Số điện thoại" required>
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Email</label>
                                <input type="email" class="form-control" name="email" placeholder="Email" required>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">

                            <div class="mb-3">
                                <label class="form-label">Địa chỉ</label>
                                <input type="text" class="form-control" name="address" placeholder="Địa chỉ" required>
                            </div>
                           
                        </div>
                    </div>
                </div>
               
            </div>


            <!-- Nút hành động -->
            <div class="d-flex justify-content-between">
                <a asp-asp-controller="Supplier" asp-action="" type="button" class="btn btn-outline-secondary" >Hủy</a>
                <button type="submit" class="btn btn-primary">Thêm danh mục</button>
            </div>
        </form>
    </div>
</div>
</div>
</div>

Warehouse.MVC/Views/Supplier/Index.cshtml
@model Warehouse.MVC.Models.SupplierView
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Nhà cung cấp</h3>
        </div>
        <div class="card-body">
            <!-- Form lọc -->
            <form id="filterForm" method="get" asp-action="Index" asp-controller="Supplier">
                <!-- Thanh tìm kiếm -->
                <div class="search-bar">
                    <div class="input-group">
                        <input type="text" class="form-control" name="search" value="@ViewBag.Search" placeholder="Tìm kiếm theo tên, SĐT, email...">
                        <button class="btn btn-outline-secondary" type="submit">
                            <i class="bi bi-search"></i> Tìm kiếm (Ctrl + K)
                        </button>
                    </div>
                </div>
            </form>
            <div class="d-flex justify-content-between mb-3">
                <a asp-controller="Supplier" asp-action="Create" class="btn btn-primary">Thêm NCC</a>
                <button id="deleteSelectedBtn" class="btn btn-danger" style="display: none;" onclick="deleteSelectedCategories()">Xóa</button>
            </div>

            <form id="deleteForm" data-delete-url="@Url.Action("DeleteMultiple", "Category")">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Tên NCC</th>
                            <th>Số điện thoại</th>
                            <th>Email</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model.Suppliers != null && Model.Suppliers.Any())
                        {
                            @foreach (var supplier in Model.Suppliers)
                            {
                                <tr>
                                    
                                    <td>
                                        <a style="text-decoration:none;" asp-controller="Supplier" asp-action="Update" asp-route-id="@supplier.SupplierId" class="product-link">
                                            @supplier.Name
                                        </a>
                                    </td>
                                    <td>@supplier.Phone</td>
                                    <td>@supplier.Email</td>
                                </tr>
                            }
                        }
                        else
                        {
                            <tr>
                                <td colspan="4" class="text-center">Không có nhà cung cấp nào.</td>
                            </tr>
                        }
                    </tbody>

                </table>
                <nav aria-label="Page navigation" class="mt-auto">
                    <ul class="pagination justify-content-center">
                        <li class="page-item @(ViewBag.Page == 1 ? "disabled" : "")">
                            <a class="page-link" href="@Url.Action("Index", new { page = ViewBag.Page - 1, pageSize = 5, search = ViewBag.Search })">Previous</a>
                        </li>
                        @for (int i = 1; i <= ViewBag.TotalPages; i++)
                        {
                            <li class="page-item @(i == ViewBag.Page ? "active" : "")">
                                <a class="page-link" href="@Url.Action("Index", new { page = i, pageSize = 5, search = ViewBag.Search })">@i</a>
                            </li>
                        }
                        <li class="page-item @(ViewBag.Page == ViewBag.TotalPages ? "disabled" : "")">
                            <a class="page-link" href="@Url.Action("Index", new { page = ViewBag.Page + 1, pageSize = 5, search = ViewBag.Search })">Next</a>
                        </li>
                    </ul>
                </nav>
            </form>
        </div>
    </div>
</div>
@await Html.PartialAsync("_ToastPartial")

@section Styles {
    <link rel="stylesheet" href="~/css/category-index.css" />
}

@section Scripts {
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    
    
}

Warehouse.MVC/Views/Supplier/Update.cshtml
@model Warehouse.MVC.Models.SupplierView
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Cập nhật NCC</h3>
        </div>
        <div class="card-body">
        <form asp-action="Update" method="post" enctype="multipart/form-data">
            <!-- Thông tin sản phẩm -->
            <div class="card mb-4">
                <div class="card-header">Thông tin NCC</div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="card-body">
                            <input hidden type="text" class="form-control" value="@Model.Supplier.SupplierId" name="SupplierId">

                            <div class="mb-3">
                                <label class="form-label">Tên sản phẩm *</label>
                                <input type="text" class="form-control" value="@Model.Supplier.Name" name="name" placeholder="Tên danh mục" required>
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Phone</label>
                                <input type="text" class="form-control" value="@Model.Supplier.Phone" name="phone" placeholder="Số điện thoại" required>
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Email</label>
                                <input type="email" class="form-control" value="@Model.Supplier.Email" name="email" placeholder="Email" required>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">

                            <div class="mb-3">
                                <label class="form-label">Địa chỉ</label>
                                <input type="text" value="@Model.Supplier.Address" class="form-control" name="address" placeholder="Địa chỉ" required>
                            </div>

                        </div>
                    </div>
                </div>

            </div>


            <!-- Nút hành động -->
            <div class="d-flex justify-content-between">
                <a asp-asp-controller="Supplier" asp-action="" type="button" class="btn btn-outline-secondary">Hủy</a>
                <button type="submit" class="btn btn-primary">Lưu</button>
            </div>
        </form>
    </div>
</div>
</div>
</div>